### ISSUE TITLE
Something went wrong ... required files were not found in the specified directory ...

### ISSUE THREAD

**Issue by ouarkainfo** [aimclub/OCEANAI#59]
Hi. 
I have followed the same step as indicated in this page: "https://oceanai.readthedocs.io/en/latest/user_guide/notebooks/Prediction-get_av_union_predictions.html" 

I got the following error: 
Something went wrong ... required files were not found in the specified directory ...

Please how to fix this ? 
Thank you

**Comment by ElenaRyumina** [comment]
Dear, @ouarkainfo 

This error occurs when an incorrect directory path to the dataset is specified. Please ensure that the directory path you provide is correct. The required directory structure for depth = 1 is as follows:

-- Dataset
   |-- folder1
   |   |-- video1
   |   |-- video2
   |   |-- ...
   |   |-- videoN
   |-- ...
   |-- folderM
   |   |-- video1
   |   |-- video2
   |   |-- ...
   |   |-- videoN

**Comment by ouarkainfo** [comment]
Thank you @ElenaRyumina 
An other error: "Something went wrong ... no ground truth scores ..."
I would like to use your model to predict traits from a video of a user.
Thank you

**Comment by ElenaRyumina** [comment]
Dear, @ouarkainfo 

You can run the library on user data in two scenarios:

1. Set the **accuracy** parameter to **False** in **the _b5.get_av_union_predictions()** function. This will provide you with predicted scores for each video.
2. Calculate the accuracy by preparing a dataframe according to the template provided at "https://drive.usercontent.google.com/download?id=1s-2UhVFRaSZmTmqa3ztGPnaL_9dWFUlz&export=download&authuser=2&confirm=t&uuid=ef16d01d-40d9-4d30-a3c9-382eb4569f5a&at=AO7h07c4dLmma0g29tJXsrh2jLMF:1727196324559" and pass it to the **url_accuracy** parameter in **_b5.get_av_union_predictions()** with **accuracy = True**. This will give you both the predicted scores for each video and the model's accuracy.

Thank you for using our library. If you have any further questions, please contact us

**Comment by ouarkainfo** [comment]
Solved. thank you @ElenaRyumina
